-- Royal Uzhavan - Seed Data
-- Seeds all new animal nutrition categories and products.

-- ============================================
-- Clean existing data
-- ============================================
TRUNCATE TABLE products CASCADE;
TRUNCATE TABLE categories CASCADE;

-- ============================================
-- Categories
-- ============================================
INSERT INTO categories (name, image) VALUES
  ('Royal Cattle Feed', '/images/cattle-food.png'),
  ('Royal Hen Feed / Royal Kozhi Theevanam*', '/images/hen-food.png'),
  ('Royal Birds Food', '/images/birds-food.png'),
  ('Royal oil-cake(Punnaku)', '/images/royal-punnakku.png'),
  ('Uzhavan Thavitu Vagaigal - nutrition', '/images/royal-nutrition.png'),
  ('Cereals and Grains Category', '/images/royal-cereals.jpg'),
  ('Uzhavan Thusi Vagaigal', '/images/royal-thoosu-vagaigal.jpg'),
  ('Uzhavan Vittha Mattum Theevana Vagaigal', '/images/royal-seed-theevanam.png'),
  ('Hen and Pigeon Supplements', '/images/hen-pigeon-supplement.png')
ON CONFLICT (name) DO NOTHING;

-- ============================================
-- Products
-- ============================================
INSERT INTO products (slug, name, category_id, animal_type, price, image, tags, variants, in_stock)
VALUES
  ('royal-kalappu', 'Royal Kalappu', (SELECT id FROM categories WHERE name = 'Royal Cattle Feed'), 'Cattle', 1000.0, '/images/cattle-food.png', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('royal-standard-mix', 'Royal Standard Mix', (SELECT id FROM categories WHERE name = 'Royal Cattle Feed'), 'Cattle', 1000.0, '/images/cattle-food.png', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('royal-gold-kalappu-theevanam', 'Royal Gold Kalappu Theevanam', (SELECT id FROM categories WHERE name = 'Royal Cattle Feed'), 'Cattle', 1000.0, '/images/cattle-food.png', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('royal-arisitham', 'Royal Arisitham', (SELECT id FROM categories WHERE name = 'Royal Cattle Feed'), 'Cattle', 1000.0, '/images/cattle-food.png', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('royal-kandra-weight-gain', 'Royal Kandra Weight gain', (SELECT id FROM categories WHERE name = 'Royal Cattle Feed'), 'Cattle', 1000.0, '/images/cattle-food.png', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('royal-makka-cholam-maavu', 'Royal Makka Cholam Maavu', (SELECT id FROM categories WHERE name = 'Royal Cattle Feed'), 'Cattle', 1000.0, '/images/cattle-food.png', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('royal-makka-cholam-kurunai', 'Royal Makka Cholam Kurunai', (SELECT id FROM categories WHERE name = 'Royal Cattle Feed'), 'Cattle', 1000.0, '/images/cattle-food.png', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('royal-pre-stater', 'Royal Pre Stater', (SELECT id FROM categories WHERE name = 'Royal Hen Feed / Royal Kozhi Theevanam*'), 'Poultry', 1000.0, '/images/hen-food.png', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('royal-stater', 'Royal Stater', (SELECT id FROM categories WHERE name = 'Royal Hen Feed / Royal Kozhi Theevanam*'), 'Poultry', 1000.0, '/images/hen-food.png', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('royal-grower', 'Royal Grower', (SELECT id FROM categories WHERE name = 'Royal Hen Feed / Royal Kozhi Theevanam*'), 'Poultry', 1000.0, '/images/hen-food.png', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('royal-layer', 'Royal Layer', (SELECT id FROM categories WHERE name = 'Royal Hen Feed / Royal Kozhi Theevanam*'), 'Poultry', 1000.0, '/images/hen-food.png', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('royal-hen-crumble', 'Royal Hen Crumble', (SELECT id FROM categories WHERE name = 'Royal Hen Feed / Royal Kozhi Theevanam*'), 'Poultry', 1000.0, '/images/hen-food.png', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('royal', 'Royal கோழி தவிடு', (SELECT id FROM categories WHERE name = 'Royal Hen Feed / Royal Kozhi Theevanam*'), 'Poultry', 1000.0, '/images/hen-food.png', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('royal', 'Royal பக்கா சோளம் குருணை', (SELECT id FROM categories WHERE name = 'Royal Hen Feed / Royal Kozhi Theevanam*'), 'Poultry', 1000.0, '/images/hen-food.png', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('royal-pigeon-sf', 'Royal Pigeon SF', (SELECT id FROM categories WHERE name = 'Royal Birds Food'), 'Birds', 1000.0, '/images/birds-food.png', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('royal-pigeon-pt', 'Royal Pigeon PT', (SELECT id FROM categories WHERE name = 'Royal Birds Food'), 'Birds', 1000.0, '/images/birds-food.png', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('royal-budgies-finches-mix', 'Royal Budgies & Finches Mix', (SELECT id FROM categories WHERE name = 'Royal Birds Food'), 'Birds', 1000.0, '/images/birds-food.png', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('royal-african-cockatiel-mix', 'Royal African & Cockatiel Mix', (SELECT id FROM categories WHERE name = 'Royal Birds Food'), 'Birds', 1000.0, '/images/birds-food.png', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('royal-multi-mix-oil-cake', 'Royal Multi Mix Oil Cake', (SELECT id FROM categories WHERE name = 'Royal oil-cake(Punnaku)'), 'Livestock', 1000.0, '/images/royal-punnakku.png', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('groundnut-oil-cake', 'Groundnut Oil Cake', (SELECT id FROM categories WHERE name = 'Royal oil-cake(Punnaku)'), 'Livestock', 1000.0, '/images/royal-punnakku.png', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('groundnut-oil-cake-powder', 'Groundnut Oil Cake Powder', (SELECT id FROM categories WHERE name = 'Royal oil-cake(Punnaku)'), 'Livestock', 1000.0, '/images/royal-punnakku.png', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('mixed-sesame-oil-cake', 'Mixed Sesame Oil Cake', (SELECT id FROM categories WHERE name = 'Royal oil-cake(Punnaku)'), 'Livestock', 1000.0, '/images/royal-punnakku.png', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('sesame-oil-cake-powder', 'Sesame Oil Cake Powder', (SELECT id FROM categories WHERE name = 'Royal oil-cake(Punnaku)'), 'Livestock', 1000.0, '/images/royal-punnakku.png', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('coconut-oil-cake-copra-cake', 'Coconut Oil Cake / Copra Cake', (SELECT id FROM categories WHERE name = 'Royal oil-cake(Punnaku)'), 'Livestock', 1000.0, '/images/royal-punnakku.png', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('mustard-oil-cake', 'Mustard Oil Cake', (SELECT id FROM categories WHERE name = 'Royal oil-cake(Punnaku)'), 'Livestock', 1000.0, '/images/royal-punnakku.png', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('soya-oil-cake', 'Soya Oil Cake', (SELECT id FROM categories WHERE name = 'Royal oil-cake(Punnaku)'), 'Livestock', 1000.0, '/images/royal-punnakku.png', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('mustard-kadu-oil-cake', 'Mustard / Kadu Oil Cake', (SELECT id FROM categories WHERE name = 'Royal oil-cake(Punnaku)'), 'Livestock', 1000.0, '/images/royal-punnakku.png', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('cotton-seed-oil-cake', 'Cotton Seed Oil Cake', (SELECT id FROM categories WHERE name = 'Royal oil-cake(Punnaku)'), 'Livestock', 1000.0, '/images/royal-punnakku.png', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('wheat-brankothambu-tavudu', 'Wheat Bran(kothambu tavudu)', (SELECT id FROM categories WHERE name = 'Uzhavan Thavitu Vagaigal - nutrition'), 'Livestock', 1000.0, '/images/royal-nutrition.png', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('rice-branarisi-tavudu', 'Rice Bran(arisi tavudu)', (SELECT id FROM categories WHERE name = 'Uzhavan Thavitu Vagaigal - nutrition'), 'Livestock', 1000.0, '/images/royal-nutrition.png', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('corn-bran', 'Corn Bran', (SELECT id FROM categories WHERE name = 'Uzhavan Thavitu Vagaigal - nutrition'), 'Livestock', 1000.0, '/images/royal-nutrition.png', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('sorghum-bransingaariya-tavudu', 'Sorghum Bran(singaariya tavudu)', (SELECT id FROM categories WHERE name = 'Uzhavan Thavitu Vagaigal - nutrition'), 'Livestock', 1000.0, '/images/royal-nutrition.png', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('coarse-bran', 'Coarse Bran', (SELECT id FROM categories WHERE name = 'Uzhavan Thavitu Vagaigal - nutrition'), 'Livestock', 1000.0, '/images/royal-nutrition.png', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('maize-corn', 'Maize / Corn', (SELECT id FROM categories WHERE name = 'Cereals and Grains Category'), 'Birds', 1000.0, '/images/royal-cereals.jpg', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('broken-maize-corn-grits', 'Broken Maize / Corn Grits', (SELECT id FROM categories WHERE name = 'Cereals and Grains Category'), 'Birds', 1000.0, '/images/royal-cereals.jpg', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('maize-flour-corn-flour', 'Maize Flour / Corn Flour', (SELECT id FROM categories WHERE name = 'Cereals and Grains Category'), 'Birds', 1000.0, '/images/royal-cereals.jpg', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('white-sorghum-white-jowar', 'White Sorghum / White Jowar', (SELECT id FROM categories WHERE name = 'Cereals and Grains Category'), 'Birds', 1000.0, '/images/royal-cereals.jpg', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('red-sorghum-red-jowar', 'Red Sorghum / Red Jowar', (SELECT id FROM categories WHERE name = 'Cereals and Grains Category'), 'Birds', 1000.0, '/images/royal-cereals.jpg', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('pearl-millet-bajra', 'Pearl Millet / Bajra', (SELECT id FROM categories WHERE name = 'Cereals and Grains Category'), 'Birds', 1000.0, '/images/royal-cereals.jpg', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('finger-millet-ragi', 'Finger Millet / Ragi', (SELECT id FROM categories WHERE name = 'Cereals and Grains Category'), 'Birds', 1000.0, '/images/royal-cereals.jpg', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('foxtail-millet', 'Foxtail Millet', (SELECT id FROM categories WHERE name = 'Cereals and Grains Category'), 'Birds', 1000.0, '/images/royal-cereals.jpg', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('wheat', 'Wheat', (SELECT id FROM categories WHERE name = 'Cereals and Grains Category'), 'Birds', 1000.0, '/images/royal-cereals.jpg', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('roasted-gram-puffed-chickpea', 'Roasted Gram / Puffed Chickpea', (SELECT id FROM categories WHERE name = 'Cereals and Grains Category'), 'Birds', 1000.0, '/images/royal-cereals.jpg', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('groundnut-peanut', 'Groundnut / Peanut', (SELECT id FROM categories WHERE name = 'Cereals and Grains Category'), 'Birds', 1000.0, '/images/royal-cereals.jpg', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('green-gram-moong-dal', 'Green Gram / Moong Dal', (SELECT id FROM categories WHERE name = 'Cereals and Grains Category'), 'Birds', 1000.0, '/images/royal-cereals.jpg', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('black-chickpea-kala-chana', 'Black Chickpea / Kala Chana', (SELECT id FROM categories WHERE name = 'Cereals and Grains Category'), 'Birds', 1000.0, '/images/royal-cereals.jpg', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('white-chickpea-kabuli-chana', 'White Chickpea / Kabuli Chana', (SELECT id FROM categories WHERE name = 'Cereals and Grains Category'), 'Birds', 1000.0, '/images/royal-cereals.jpg', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('paddy-unpolished-rice-grain', 'Paddy / Unpolished Rice Grain', (SELECT id FROM categories WHERE name = 'Cereals and Grains Category'), 'Birds', 1000.0, '/images/royal-cereals.jpg', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('white-peas', 'White Peas', (SELECT id FROM categories WHERE name = 'Cereals and Grains Category'), 'Birds', 1000.0, '/images/royal-cereals.jpg', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('green-peas', 'Green Peas', (SELECT id FROM categories WHERE name = 'Cereals and Grains Category'), 'Birds', 1000.0, '/images/royal-cereals.jpg', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('red-rice', 'Red Rice', (SELECT id FROM categories WHERE name = 'Cereals and Grains Category'), 'Birds', 1000.0, '/images/royal-cereals.jpg', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('black-horse-gram-black-cowpea', 'Black Horse Gram / Black Cowpea', (SELECT id FROM categories WHERE name = 'Cereals and Grains Category'), 'Birds', 1000.0, '/images/royal-cereals.jpg', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('white-horse-gram-white-cowpea', 'White Horse Gram / White Cowpea', (SELECT id FROM categories WHERE name = 'Cereals and Grains Category'), 'Birds', 1000.0, '/images/royal-cereals.jpg', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('barley', 'Barley', (SELECT id FROM categories WHERE name = 'Cereals and Grains Category'), 'Birds', 1000.0, '/images/royal-cereals.jpg', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('black-wheat', 'Black Wheat', (SELECT id FROM categories WHERE name = 'Cereals and Grains Category'), 'Birds', 1000.0, '/images/royal-cereals.jpg', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('black-sunflower-seeds', 'Black Sunflower Seeds', (SELECT id FROM categories WHERE name = 'Cereals and Grains Category'), 'Birds', 1000.0, '/images/royal-cereals.jpg', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('striped-white-sunflower-seeds', 'Striped / White Sunflower Seeds', (SELECT id FROM categories WHERE name = 'Cereals and Grains Category'), 'Birds', 1000.0, '/images/royal-cereals.jpg', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('sorghum-millet-small-grain', 'Sorghum Millet - Small Grain', (SELECT id FROM categories WHERE name = 'Cereals and Grains Category'), 'Birds', 1000.0, '/images/royal-cereals.jpg', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('flat-bean-field-bean', 'Flat Bean / Field Bean', (SELECT id FROM categories WHERE name = 'Cereals and Grains Category'), 'Birds', 1000.0, '/images/royal-cereals.jpg', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('little-millet', 'Little Millet', (SELECT id FROM categories WHERE name = 'Cereals and Grains Category'), 'Birds', 1000.0, '/images/royal-cereals.jpg', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('kodo-millet', 'Kodo Millet', (SELECT id FROM categories WHERE name = 'Cereals and Grains Category'), 'Birds', 1000.0, '/images/royal-cereals.jpg', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('barnyard-millet', 'Barnyard Millet', (SELECT id FROM categories WHERE name = 'Cereals and Grains Category'), 'Birds', 1000.0, '/images/royal-cereals.jpg', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('proso-millet', 'Proso Millet', (SELECT id FROM categories WHERE name = 'Cereals and Grains Category'), 'Birds', 1000.0, '/images/royal-cereals.jpg', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('linseed-groundnut-kernels', 'Linseed & Groundnut Kernels', (SELECT id FROM categories WHERE name = 'Cereals and Grains Category'), 'Birds', 1000.0, '/images/royal-cereals.jpg', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('oats', 'Oats', (SELECT id FROM categories WHERE name = 'Cereals and Grains Category'), 'Birds', 1000.0, '/images/royal-cereals.jpg', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('sesame-seed', 'Sesame Seed', (SELECT id FROM categories WHERE name = 'Cereals and Grains Category'), 'Birds', 1000.0, '/images/royal-cereals.jpg', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('niger-seed', 'Niger Seed', (SELECT id FROM categories WHERE name = 'Cereals and Grains Category'), 'Birds', 1000.0, '/images/royal-cereals.jpg', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('rapeseed', 'Rapeseed', (SELECT id FROM categories WHERE name = 'Cereals and Grains Category'), 'Birds', 1000.0, '/images/royal-cereals.jpg', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('mustard-seed', 'Mustard Seed', (SELECT id FROM categories WHERE name = 'Cereals and Grains Category'), 'Birds', 1000.0, '/images/royal-cereals.jpg', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('buckwheat', 'Buckwheat', (SELECT id FROM categories WHERE name = 'Cereals and Grains Category'), 'Birds', 1000.0, '/images/royal-cereals.jpg', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('quinoa', 'Quinoa', (SELECT id FROM categories WHERE name = 'Cereals and Grains Category'), 'Birds', 1000.0, '/images/royal-cereals.jpg', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('chia-seed', 'Chia Seed', (SELECT id FROM categories WHERE name = 'Cereals and Grains Category'), 'Birds', 1000.0, '/images/royal-cereals.jpg', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('pumpkin-seed', 'Pumpkin Seed', (SELECT id FROM categories WHERE name = 'Cereals and Grains Category'), 'Birds', 1000.0, '/images/royal-cereals.jpg', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('flax-seed-lin-seed', 'Flax Seed / Lin Seed', (SELECT id FROM categories WHERE name = 'Cereals and Grains Category'), 'Birds', 1000.0, '/images/royal-cereals.jpg', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('vetch-seed', 'Vetch Seed', (SELECT id FROM categories WHERE name = 'Cereals and Grains Category'), 'Birds', 1000.0, '/images/royal-cereals.jpg', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('maple-peas', 'Maple Peas', (SELECT id FROM categories WHERE name = 'Cereals and Grains Category'), 'Birds', 1000.0, '/images/royal-cereals.jpg', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('austrian-peas', 'Austrian Peas', (SELECT id FROM categories WHERE name = 'Cereals and Grains Category'), 'Birds', 1000.0, '/images/royal-cereals.jpg', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('white-millets', 'White Millets', (SELECT id FROM categories WHERE name = 'Cereals and Grains Category'), 'Birds', 1000.0, '/images/royal-cereals.jpg', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('red-millets', 'Red Millets', (SELECT id FROM categories WHERE name = 'Cereals and Grains Category'), 'Birds', 1000.0, '/images/royal-cereals.jpg', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('japanese-millet', 'Japanese Millet', (SELECT id FROM categories WHERE name = 'Cereals and Grains Category'), 'Birds', 1000.0, '/images/royal-cereals.jpg', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('yellow-millet', 'Yellow Millet', (SELECT id FROM categories WHERE name = 'Cereals and Grains Category'), 'Birds', 1000.0, '/images/royal-cereals.jpg', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('cardi-seed', 'Cardi Seed', (SELECT id FROM categories WHERE name = 'Cereals and Grains Category'), 'Birds', 1000.0, '/images/royal-cereals.jpg', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('small-black-sunflower', 'Small Black Sunflower', (SELECT id FROM categories WHERE name = 'Cereals and Grains Category'), 'Birds', 1000.0, '/images/royal-cereals.jpg', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('white-sunflower', 'White Sunflower', (SELECT id FROM categories WHERE name = 'Cereals and Grains Category'), 'Birds', 1000.0, '/images/royal-cereals.jpg', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('canary-seed', 'Canary Seed', (SELECT id FROM categories WHERE name = 'Cereals and Grains Category'), 'Birds', 1000.0, '/images/royal-cereals.jpg', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('black-gram-husk-powder', 'Black Gram Husk Powder', (SELECT id FROM categories WHERE name = 'Uzhavan Thusi Vagaigal'), 'Livestock', 1000.0, '/images/royal-thoosu-vagaigal.jpg', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('black-gram-small-broken-powder', 'Black Gram Small Broken / Powder', (SELECT id FROM categories WHERE name = 'Uzhavan Thusi Vagaigal'), 'Livestock', 1000.0, '/images/royal-thoosu-vagaigal.jpg', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('black-gram-broken-waste-mix', 'Black Gram Broken & Waste Mix', (SELECT id FROM categories WHERE name = 'Uzhavan Thusi Vagaigal'), 'Livestock', 1000.0, '/images/royal-thoosu-vagaigal.jpg', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('cowpea-lobia-husk-powder', 'Cowpea / Lobia Husk Powder', (SELECT id FROM categories WHERE name = 'Uzhavan Thusi Vagaigal'), 'Livestock', 1000.0, '/images/royal-thoosu-vagaigal.jpg', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('black-green-gram-broken-waste', 'Black Green Gram Broken Waste', (SELECT id FROM categories WHERE name = 'Uzhavan Thusi Vagaigal'), 'Livestock', 1000.0, '/images/royal-thoosu-vagaigal.jpg', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('black-karamani-black-cowpea-husk', 'Black Karamani / Black Cowpea Husk', (SELECT id FROM categories WHERE name = 'Uzhavan Thusi Vagaigal'), 'Livestock', 1000.0, '/images/royal-thoosu-vagaigal.jpg', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('dried-peas-husk', 'Dried Peas Husk', (SELECT id FROM categories WHERE name = 'Uzhavan Thusi Vagaigal'), 'Livestock', 1000.0, '/images/royal-thoosu-vagaigal.jpg', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('toor-dal-pigeon-pea-husk', 'Toor Dal / Pigeon Pea Husk', (SELECT id FROM categories WHERE name = 'Uzhavan Thusi Vagaigal'), 'Livestock', 1000.0, '/images/royal-thoosu-vagaigal.jpg', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('masoor-dal-lentil-husk', 'Masoor Dal / Lentil Husk', (SELECT id FROM categories WHERE name = 'Uzhavan Thusi Vagaigal'), 'Livestock', 1000.0, '/images/royal-thoosu-vagaigal.jpg', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('millet-husk-powder', 'Millet Husk Powder', (SELECT id FROM categories WHERE name = 'Uzhavan Thusi Vagaigal'), 'Livestock', 1000.0, '/images/royal-thoosu-vagaigal.jpg', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('mixed-grains-husk-powder', 'Mixed Grains Husk Powder', (SELECT id FROM categories WHERE name = 'Uzhavan Thusi Vagaigal'), 'Livestock', 1000.0, '/images/royal-thoosu-vagaigal.jpg', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('tamarind-seed-broken-crush', 'Tamarind Seed Broken / Crush', (SELECT id FROM categories WHERE name = 'Uzhavan Vittha Mattum Theevana Vagaigal'), 'Livestock', 1000.0, '/images/royal-seed-theevanam.png', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('tamarind-seed-broken', 'Tamarind Seed Broken', (SELECT id FROM categories WHERE name = 'Uzhavan Vittha Mattum Theevana Vagaigal'), 'Livestock', 1000.0, '/images/royal-seed-theevanam.png', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('tamarind-seed-powder', 'Tamarind Seed Powder', (SELECT id FROM categories WHERE name = 'Uzhavan Vittha Mattum Theevana Vagaigal'), 'Livestock', 1000.0, '/images/royal-seed-theevanam.png', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('cotton-seed-cake', 'Cotton Seed Cake', (SELECT id FROM categories WHERE name = 'Uzhavan Vittha Mattum Theevana Vagaigal'), 'Livestock', 1000.0, '/images/royal-seed-theevanam.png', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('country-cotton-seed-desi-cotton-seed', 'Country Cotton Seed / Desi Cotton Seed', (SELECT id FROM categories WHERE name = 'Uzhavan Vittha Mattum Theevana Vagaigal'), 'Livestock', 1000.0, '/images/royal-seed-theevanam.png', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('black-cotton-seed', 'Black Cotton Seed', (SELECT id FROM categories WHERE name = 'Uzhavan Vittha Mattum Theevana Vagaigal'), 'Livestock', 1000.0, '/images/royal-seed-theevanam.png', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('pigeon-grit', 'Pigeon Grit', (SELECT id FROM categories WHERE name = 'Hen and Pigeon Supplements'), 'Birds', 1000.0, '/images/hen-pigeon-supplement.png', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('calcium-tonic', 'Calcium Tonic', (SELECT id FROM categories WHERE name = 'Hen and Pigeon Supplements'), 'Birds', 1000.0, '/images/hen-pigeon-supplement.png', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('calcium-powder', 'Calcium Powder', (SELECT id FROM categories WHERE name = 'Hen and Pigeon Supplements'), 'Birds', 1000.0, '/images/hen-pigeon-supplement.png', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('mineral-mixture', 'Mineral Mixture', (SELECT id FROM categories WHERE name = 'Hen and Pigeon Supplements'), 'Birds', 1000.0, '/images/hen-pigeon-supplement.png', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('salt', 'Salt', (SELECT id FROM categories WHERE name = 'Hen and Pigeon Supplements'), 'Birds', 1000.0, '/images/hen-pigeon-supplement.png', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('liver-tonic', 'Liver Tonic', (SELECT id FROM categories WHERE name = 'Hen and Pigeon Supplements'), 'Birds', 1000.0, '/images/hen-pigeon-supplement.png', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('kadal-chippi-powder', 'Kadal chippi, powder', (SELECT id FROM categories WHERE name = 'Hen and Pigeon Supplements'), 'Birds', 1000.0, '/images/hen-pigeon-supplement.png', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true),
  ('kanava-thoodu', 'Kanava thoodu', (SELECT id FROM categories WHERE name = 'Hen and Pigeon Supplements'), 'Birds', 1000.0, '/images/hen-pigeon-supplement.png', ARRAY['Royal Uzhavan Quality'], ARRAY[1, 5, 25], true)
ON CONFLICT (slug) DO NOTHING;
